/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Demand = IDL.Record({
  'consent' : IDL.Bool,
  'timing' : IDL.Text,
  'name' : IDL.Text,
  'need' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'budget' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const Provider = IDL.Record({
  'categories' : IDL.Vec(IDL.Text),
  'consent' : IDL.Bool,
  'city' : IDL.Text,
  'businessName' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'serviceAreas' : IDL.Text,
});

export const idlService = IDL.Service({
  'getDemand' : IDL.Func([IDL.Nat], [Demand], []),
  'getDemands' : IDL.Func([], [IDL.Vec(Demand)], []),
  'getProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
  'postDemand' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'registerProvider' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Demand = IDL.Record({
    'consent' : IDL.Bool,
    'timing' : IDL.Text,
    'name' : IDL.Text,
    'need' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'budget' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const Provider = IDL.Record({
    'categories' : IDL.Vec(IDL.Text),
    'consent' : IDL.Bool,
    'city' : IDL.Text,
    'businessName' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'serviceAreas' : IDL.Text,
  });
  
  return IDL.Service({
    'getDemand' : IDL.Func([IDL.Nat], [Demand], []),
    'getDemands' : IDL.Func([], [IDL.Vec(Demand)], []),
    'getProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
    'postDemand' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'registerProvider' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };