/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Demand {
  'consent' : boolean,
  'timing' : string,
  'name' : string,
  'need' : string,
  'timestamp' : bigint,
  'phone' : string,
  'budget' : [] | [string],
  'location' : string,
}
export interface Provider {
  'categories' : Array<string>,
  'consent' : boolean,
  'city' : string,
  'businessName' : string,
  'timestamp' : bigint,
  'phone' : string,
  'serviceAreas' : string,
}
export interface _SERVICE {
  'getDemand' : ActorMethod<[bigint], Demand>,
  'getDemands' : ActorMethod<[], Array<Demand>>,
  'getProviders' : ActorMethod<[], Array<Provider>>,
  'postDemand' : ActorMethod<
    [string, string, string, string, string, [] | [string], boolean],
    bigint
  >,
  'registerProvider' : ActorMethod<
    [string, string, string, Array<string>, string, boolean],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];